config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about' => 'pages#about'
  
  resources :contacts 

  

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  
  has_many :donations
  
  validates :last_name, presence: true, length: {minimum: 2, maximum: 15}
  validates :first_name, presence: true, length: {minimum: 2, maximum: 15}
  
end

app/models/donation.rb
class Donation < ActiveRecord::Base
  
  belongs_to :contact
  
  validates :donation_date, :amount, presence: true
  validates :contact_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]
  def index
    @contacts = Contact.all
  end
  
  def show
    
  end
  
  def new
    @contact = Contact.new
  end
  
  def edit
   
  end
  
  def create
    
    @contact = Contact.new(contact_params)

    if @contact.save
      flash[:success] = "Contact was successfully created."
      redirect_to contact_path(@contact)
      
    else
      
      render 'new'
    end
  end
  
  def update
    
    
    if @contact.update(contact_params)
      flash[:success] = "Contact was updated successfully."
      redirect_to contact_path(@contact)
      
    else
      render 'edit'
    end
  end
  
  def destroy
    
    @contact.destroy
    flash[:danger] = "Contact was successfully destroyed."
    
    redirect_to contacts_path
  end
  
  private
  
  def set_contact
    @contact = Contact.find(params[:id])
  end
  
  def contact_params
    params.require(:contact).permit(:first_name, :last_name, :address, :city, :state, :zip)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
  end
  
  def about
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/_form.html.erb
<%= render 'shared/errors', obj: @contact %>

<div class="row">
  <div class="col-sm-12">
    <%= form_for(@contact, :html => {class: "form-horizontal", role: "form"}) do |f| %>

    
        <div class="form-group">
              
      
                <div class="col-xs-3 col-xs-offset-3">
                   <%= f.text_field :first_name, class: "form-control", placeholder: "First Name", autofocus: true %>
                </div>


                <div class="col-xs-3">
                   <%= f.text_field :last_name, class: "form-control", placeholder: "Last Name"%>
                </div>
        </div>
 

         
      
               <div class="form-group">
                                
                  <div class= "col-xs-offset-3 col-xs-6">
                     <%= f.text_field :address, class: "form-control", placeholder: "Address"%>
                  </div>
                </div>
            
    
                <div class="form-group">
                  <div class="col-xs-offset-3 col-xs-3">
                     <%= f.text_field :city, class: "form-control", placeholder: "City" %>
                  </div>


                  <div class="col-xs-1">
                     <%= f.text_field :state, class: "form-control", placeholder: "State" %>
                  </div>
          
                  <div class="col-xs-2">
                      <%= f.text_field :zip, class: "form-control", placeholder: "Zipcode" %>
                  </div>
          
               </div>
    
    
              <div class="form-group">

                  <div class="col-xs-offset-3 col-xs-9">

                     <%= f.submit class: 'btn btn-primary btn-lg' %>

                  </div>
            </div>

<% end %>
 </div>
</div>

  <div class="col-md-4 col-md-offset-4">
     [ <%= link_to "Cancel request and return to Contacts List", contacts_path %> ]
  </div>

  </div>
</div>

app/views/contacts/edit.html.erb
<h1 align="center">Edit This Contact</h1>

<%= render 'form' %>

app/views/contacts/index.html.erb
<h1 align="center">Contacts</h1>

<p>
  <%= link_to "Create new contact", new_contact_path, class: "btn btn-xs btn-success" %>
</p>
<div class="row">
  <div class="col-xs-11">
    <table class="table table-striped">
        <div class="contact-headers">
      <tr>
          <th>Contact Name</th>
          <th>Address</th>
          <th>City</th>
          <th>State</th>
          <th>Zip</th>
      </tr>
        </div>
    <% @contacts.each do |contact| %>
       <div class="contact-body">
     <tr>
       <td><%= link_to "#{contact.first_name} #{contact.last_name}", contact_path(contact) %></td>
      
       <td><%= contact.address %></td>
       <td><%= contact.city %></td>
       <td><%= contact.state %></td>
       <td><%= contact.zip %> </td> 
       
       
    </tr>
    </div>
    </div>
    
    <% end %>
  
  
</table>

</div>

app/views/contacts/new.html.erb
<h1 align="center">Create Contact</h1>


<%= render 'form' %>

app/views/contacts/show.html.erb
<h2 align="center"><%= @contact.first_name %> <%= @contact.last_name %> </h2> <br/>

<div class="well col-md-10 col-md-offset-2">
  <h4 class="address-label"><strong>Address:</strong></h4>
  

<%= @contact.address %> <br/>
<%= @contact.city %>, <%= @contact.state %> <%= @contact.zip %></p>
 
  
<div class="contact-actions">
<%= link_to "Edit this Contact", edit_contact_path(@contact), class: "btn btn-xs btn-primary" %> 
<%= link_to "Delete this Contact", contact_path(@contact), 
          method: :delete, data: { confirm: "Are you sure you want to delete this contact?"},
          class: "btn btn-xs btn-danger" %>
<%= link_to "View All Contacts", contacts_path, class: "btn btn-xs btn-success" %>

</div>

</div>

app/views/layouts/_footer.html.erb
<div class="container">
  
  <footer class="footer">
    <small>Copywrite &copy; by <a href="http://martymooradian.com">Marty Mooradian</a>. All rights reserved.</small>
    <nav>
      <ul>
        <li><%= link_to "About", about_path %></li>
      </ul>
    </nav>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%="#{name}" %>'>
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
      <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "NeeYo CRM", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
     <ul class="nav navbar-nav">
        
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>
          <ul class="dropdown-menu">
  
            <li><%= link_to "Add New Contact", new_contact_path %></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-right">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "About Us", about_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <%= render 'layouts/navigation' %>
  <%= render 'layouts/messages' %>

<div class="container">
  <%= yield %>
</div>

<%= render 'layouts/footer' %>
<%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/pages/about.html.erb
<h1>This is the about page</h1>

<%= link_to 'Home', root_path %>

app/views/pages/home.html.erb
<h1></h1>




<div class="center jumbotron">
  <h1>Welcome to NeeYo!</h1>
  <h3>Your light-weight CRM</h3>
  
  <%= link_to "Sign up now!", "#", class: "btn btn-primary btn-lg" %>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= pluralize(obj.errors.count, "error") %>
              prohibited this contact from being saved:
          </h2>
          
          <div class="panel-body">
            <ul>
              	<% obj.errors.full_messages.each do |msg| %>
			            <li><%= msg %></li>
		            <% end %>
            </ul>
          </div> 
        </div>
      </div>
    </div>
  </div>

<% end %>